Trigger times added to Neuland
R3BRootGroup/R3BRoot pull request #662
Opened 2022-09-29 14:00 UTC by igasparic

- in reader NeulandTrigMappedData + option fSkiptriggertime
- Mapped2CalPar
- Mapped2Cal - fTriggerTime in NeulandCalData - mapping_neuland_trig.hh hardcoded
- Cal2HitPar, Cal2Hit - trigger time subtracted

NeulandOnlineSpectra updated

GainMatching modified in preexp

Clang-format

2022-09-29 15:37 UTC, jose-luis-rs requested changes

2022-09-29 15:37 UTC, jose-luis-rs commented on neuland/calibration/R3BNeulandMapped2Cal.cxx
> +#include "mapping_neuland_trig.hh"
I am wondering if this file depends on the experiment, if yes, it must be read from a parameter container. This kind of container was already created for other detectors like Fibers and TofD:
- https://github.com/R3BRootGroup/R3BRoot/blob/dev/tofd/pars/R3BTofDMappingPar.h
- https://github.com/R3BRootGroup/R3BRoot/blob/dev/fiber/pars/R3BFiberMappingPar.h

2022-09-30 10:05 UTC, jose-luis-rs commented on neuland/calibration/R3BNeulandMapped2Cal.cxx
> +#include "mapping_neuland_trig.hh"
There are also some examples of macros to convert the ucesb mapping files into r3broot parameter files:
https://github.com/R3BRootGroup/R3BParams_S515/blob/dev/macros/calibration/fibers/make_fiber_trig_mapping.C
https://github.com/R3BRootGroup/R3BParams_S515/blob/dev/macros/calibration/tofd/make_tofd_trig_mapping.C

2022-09-30 13:46 UTC, YanzhaoW reviewed
I think there is no necessity to change anything in Cal2Hit file if we redefine the `GetTime()` to the triggered time value.

2022-09-30 13:46 UTC, YanzhaoW commented on r3bdata/neulandData/R3BNeulandCalData.h
>      Double_t GetTime() const { return fTime; }
Redefine GetTime method to get triggered time. Also add another getter for untriggered time:
```suggestion
    Double_t GetTime() const { return fTime - fTriggerTime; }
    Double_t GetTimeUntriggered() const { return fTime; }
```

2022-09-30 13:46 UTC, YanzhaoW commented on r3bdata/neulandData/R3BNeulandCalData.cxx
>  }
Add a second constructor for the sake of backward compatibility.
```suggestion
R3BNeulandCalData::R3BNeulandCalData(Int_t barId, Int_t side, Double_t time, Double_t triggertime, Int_t qdc)
    : fBarId(barId)
    , fSide(side)
    , fTime(time)
    , fTriggerTime(triggertime)
    , fQdc(qdc)
{
}

R3BNeulandCalData::R3BNeulandCalData(Int_t barId, Int_t side, Double_t time, Int_t qdc)
    : R3BNeulandCalData(barId, side, time, 0.0, qdc)
{
}
```

2022-09-30 13:46 UTC, YanzhaoW commented on r3bdata/neulandData/R3BNeulandCalData.h
> +    R3BNeulandCalData(Int_t barId, Int_t side, Double_t time, Double_t triggertime, Int_t qdc);
```suggestion
    R3BNeulandCalData(Int_t barId, Int_t side, Double_t time, Double_t triggertime, Int_t qdc);
    R3BNeulandCalData(Int_t barId, Int_t side, Double_t time, Int_t qdc);
```

2022-09-30 13:46 UTC, YanzhaoW commented on neuland/calibration/R3BNeulandCal2Hit.cxx
> +        }
Such a change in unnecessary if we just set the default value of triggerTime to 0.

2022-09-30 13:46 UTC, YanzhaoW commented on neuland/calibration/R3BNeulandCal2HitPar.cxx
> +        }
Also not necessary if the default value of triggerTime is 0.

2022-09-30 15:05 UTC, YanzhaoW reviewed
Some suggestions in MappedToCal file.

2022-09-30 16:03 UTC, igasparic commented
Thanks for the suggestions. A new pull request is created but only with fixes related to Jose Luis' comments. I will take care of Yanzhao's comments in future.

2022-10-03 14:30 UTC, jose-luis-rs commented
Hi
This PR and #664 are the same, right?
Can I close this one?
Cheers

2022-10-03 14:37 UTC, igasparic commented
Yes, close this one. #664 contains everything from here and R3BNeulandMappingPar stuff in addition.

2022-10-03 14:39 UTC, closed without merging