TTT10 reader
R3BRootGroup/R3BRoot pull request #912
Opened 2023-12-04 17:15 UTC by mwhiteheadyork

Added Mapped level and reader for TTT10.

Mention any issue this PR is resolved or is related to.

---

Checklist:

* [x] Rebased against `dev` branch
* [x] My name is in the resp. CONTRIBUTORS/AUTHORS file
* [x] Followed the [pull request guidlines](https://opensource.creativecommons.org/contributing-code/pr-guidelines/) and the [Git workflow](https://github.com/AnarManafov/GitWorkflow/blob/master/GitWorkflow.markdown)
* [x] Followed the [seven rules of great commit messages](https://chris.beams.io/posts/git-commit/#seven-rules)

2023-12-20 20:52 UTC, jose-luis-rs requested changes

2023-12-20 20:52 UTC, jose-luis-rs commented on r3bdata/ttt10Data/R3BTTTXMappedData.cxx
> +    , fChannelID(0)
fChannelID should be fStripID because this is for a silicon detector with 32 strips, right?

2023-12-20 20:52 UTC, jose-luis-rs commented on r3bdata/ttt10Data/R3BTTTXMappedData.cxx
> +    , fChannelID(ChannelID)
same

2023-12-20 20:52 UTC, jose-luis-rs commented on r3bdata/ttt10Data/R3BTTTXMappedData.h
> +     *@param ChannelID  Channel ID attention 0-based !
StripID in 1-based instead of 0-based

2023-12-20 20:52 UTC, jose-luis-rs commented on r3bdata/ttt10Data/R3BTTTXMappedData.h
> +    inline const UInt_t& GetChannelID() const { return fChannelID; }
GetStripID

2023-12-20 20:52 UTC, jose-luis-rs commented on r3bdata/ttt10Data/R3BTTTXMappedData.h
> +    void SetChannelID(UInt_t id) { fChannelID = id; };
SetStripID

2023-12-20 20:52 UTC, jose-luis-rs commented on r3bdata/ttt10Data/R3BTTTXMappedData.h
> +    UInt_t fChannelID;
fStripID

2024-01-04 16:09 UTC, mwhiteheadyork commented
Hi @jose-luis-rs, the changes have been made and should be ready to merge.

2024-01-04 16:35 UTC, merged