Create R3BTttxOnlineSpectra
R3BRootGroup/R3BRoot pull request #953
Opened 2024-01-23 15:41 UTC by mwhiteheadyork

Created Online Spectra for TTT10.

---

Checklist:

* [x] Rebased against `dev` branch
* [x] My name is in the resp. CONTRIBUTORS/AUTHORS file
* [x] Followed the [pull request guidlines](https://opensource.creativecommons.org/contributing-code/pr-guidelines/) and the [Git workflow](https://github.com/AnarManafov/GitWorkflow/blob/master/GitWorkflow.markdown)
* [x] Followed the [seven rules of great commit messages](https://chris.beams.io/posts/git-commit/#seven-rules)

2024-01-23 16:09 UTC, jose-luis-rs requested changes

2024-01-23 16:09 UTC, jose-luis-rs commented on tttx/online/R3BTttxOnlineSpectra.cxx
> +    TFolder* mainfolTttx = new TFolder("TTT10", "TTT10 info");
"TTTX" for the folder name could be better.

2024-01-23 16:09 UTC, jose-luis-rs commented on tttx/online/R3BTttxOnlineSpectra.cxx
> +    if (!header)
delete these two lines:
if (!header)
header = dynamic_cast<R3BEventHeader*>(rootManager->GetObject("R3BEventHeader"));

they are not needed anymore

2024-01-23 16:09 UTC, jose-luis-rs commented on tttx/online/R3BTttxOnlineSpectra.cxx
> +#include "R3BTttxMappedData.h"
Add also:
#include "R3BShared.h"

2024-01-23 16:09 UTC, jose-luis-rs commented on tttx/online/R3BTttxOnlineSpectra.cxx
> +        fh2_EnergyVsStrip_recent[i] = new TH2F(Name1, Name2, fNbStrips, 1, fNbStrips + 1, binsE, minE, maxE);
use:
"R3B::root_owned<TH2F>"
instead of:
"new TH2F"

2024-01-23 16:09 UTC, jose-luis-rs commented on tttx/online/R3BTttxOnlineSpectra.cxx
> +        fh2_EnergyVsStrip_all[i] = new TH2F(Name1, Name2, fNbStrips, 1, fNbStrips + 1, binsE, minE, maxE);
Use:
"R3B::root_owned<TH2F>"
instead of 
"new TH2F"

2024-01-23 16:09 UTC, jose-luis-rs commented on tttx/online/R3BTttxOnlineSpectra.cxx
> +        fh1_Strip[i] = new TH1F(Name1, Name2, fNbStrips, 1, fNbStrips + 1);
Use:
"R3B::root_owned<TH1F>"
instead of
"new TH1F"

2024-01-23 16:09 UTC, jose-luis-rs commented on tttx/online/R3BTttxOnlineSpectra.h
> +#define R3BTttxOnlineSpectra_H 1
#pragma once
instead of 
#ifndef R3BTttxOnlineSpectra_H
#define R3BTttxOnlineSpectra_H 1

2024-01-23 16:09 UTC, jose-luis-rs commented on tttx/online/R3BTttxOnlineSpectra.h
> +#endif
delete  #endif

2024-01-26 00:17 UTC, jose-luis-rs commented on tttx/online/R3BTttxOnlineSpectra.cxx
> +            fh2_MultVsStrip[i_det]->Fill(i_strip + 1, mult[i_det][i_strip]);
if (mult[i_det][i_strip] > 0)
    fh2_MultVsStrip[i_det]->Fill(i_strip + 1, mult[i_det][i_strip]);

2024-01-26 00:17 UTC, jose-luis-rs commented on tttx/online/R3BTttxOnlineSpectra.cxx
> +            fh2_TimeVsStrip[i_det]->Fill(i_strip + 1,
if (time[i_det][i_strip] != NAN && time[i_det][fNbStrips + fNbTref] != NAN)

2024-01-31 15:35 UTC, ryotani commented
@jose-luis-rs I hope there's no conflict with the recent updates in dev, but let us know if we need to rebase.

2024-01-31 16:57 UTC, merged